# Generated by Django 4.2.3 on 2023-07-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqs_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuemodel',
            old_name='updated_ta',
            new_name='updated_at',
        ),
    ]
