# Generated by Django 4.2.3 on 2023-07-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs_queue', '0002_rename_updated_ta_queuemodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemodel',
            name='queue_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
